name: Testing Github Actions
run-name: ${{ github.actor }}; Testing
on: [push]
jobs:
  FirstGithubAction:
    runs-on: ubuntu-latest
    steps:
      - run: git checkout
      - run: echo "Running on repository ${{github.repository}} and on branch ${{github.ref}}"
      - run: ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
