name: Issue Priority Level Assigner

on:
  issues:
    types: [opened, labeled]

jobs:
  set_priority_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'bug' }}
    
    
    steps:
      - name: Parse Issue Form (Get Priority Value)
        id: form_parser
        uses: stefanbuck/github-issue-parser@v3 
        with:
          issue_body: ${{ github.event.issue.body }}
          
      - name: Determine Priority Label
        id: priority_label_setter
        run: |
          PRIORITY_LABEL="${{ steps.form_parser.outputs.priority }}"
          echo "priority_label=$PRIORITY_LABEL" >> $GITHUB_OUTPUT
          
      - name: Apply Priority Label to Issue
        uses: actions/github-script@v6
        with:
          script: |
            // This applies the P0, P1, P2, or P3 label to the issue
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['${{ steps.priority_label_setter.outputs.priority_label }}']
            })
